# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: ibmcase
  name: wfd-appetizer
  tag: spring-cloud
  pullPolicy: Always
  containerPort: 8081
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
service:
  name: Node
  type: ClusterIP
  servicePort: 8081
zipkin:
  service: spring-stack-zipkin-server
  port: 9411
eureka:
  service: spring-stack-spring-eureka-server
  port: 8761
  preferIpAddress: true
config:
  service: spring-stack-spring-config-server
  port: 8888
  branch: spring-cloud
